### PR TITLE
Update database.json

### PR DESCRIPTION
**Pull request by DannyKokkinos**
Updated database.json to point towards the new mezzanine content for CAAC, CAAA and CAMC

### CODE REVIEW

**Comment by rbouqueau** [comment]
The PR in itself is ok.

FYI I curl randomly [a mpd](https://dash.akamaized.net/WAVE/vectors/releases/1/camc_sets/he_aac/at12/2023-04-27/stream.mpd) and I saw this:
```
    <SegmentTimeline>
     <S t="0" d="89150"/>
     <S d="94208" r="13"/>
     <S d="31938"/>
    </SegmentTimeline>
```

Does this pattern looks ok to you?

**Comment by DannyKokkinos** [comment]
Yes that pattern is correct.

**Comment by rbouqueau** [comment]
@nicholas-fr Do you confirm it looks ok ?

Then we can merge.

**Comment by rbouqueau** [comment]
I merged it but your first segment duration is shorter than the other ones. This doesn't look good to me.

**Comment by nicholas-fr** [comment]
The current validation script does not yet support audio test vectors, and needs more work (also for video).
I would expect consistent segment durations, based on our past discussions and validation of video test vectors.

Have these new test vectors at least passed JCCP validation? 
I believe we had agreed that passing JCCP validation (or having bugs logged for any issues) was an acceptance criteria for new test content.

**Comment by haudiobe** [comment]
As discussed in the DPCTF call, it would be great to attach JCCP test reports with submitted material. Can we establish such a process?

**Comment by michael-forsyth** [comment]
Concerning the segment lengths.

The aac codecs add padding to the start of the audio. 
This is compensated for by an editlist box in the init segment informing the player to skip the padding during playback.
This means the encoded and playback duration are different for the audio.
As the fragmentation and segmentation is based on the encoded duration this results in the first segment having a shorter playback duration as shown in the MPD when the encoded duration of each segment is constant. 
Therefore the first segment being shorter in the MPD by an amount equal to the padding is expected.

**Comment by rbouqueau** [comment]
> As the fragmentation and segmentation is based on the encoded duration this results in the first segment having a shorter playback duration

Well it is based on whatever the muxing implementation does. I checked for GPAC and we changed the behaviour [last December](https://github.com/gpac/gpac/commit/f6f6ce3f0c78603287ce9033561d35354739a1ea) following a request from Fraunhofer for MPEG-H. 

I don't think that was correct for older codecs. We discussed. And [the old behaviour is back](https://github.com/gpac/gpac/commit/edc6d8aa91e3ddd1f78df9748ea76991f05d4134) for most codecs.

Both results are correct. But if the validation script expects "consistent segment durations" (as @nicholas-fr said) we should consider regenerating.

**Comment by nicholas-fr** [comment]
> Both results are correct. But if the validation script expects "consistent segment durations" (as @nicholas-fr said) we should consider regenerating.

I can adapt the validation script as needed. I anyway need to add proper support for the audio test streams.

**Pull request merged**
