### PR TITLE
Update database.json

### PR DESCRIPTION
**Pull request by rcottingham**
Added:
* AAC at2 (chunked), at15 (spliced main encrypted), at16 (spliced ad encrypted)
* AC4 at1-4
* EAC3 at1-4

### CODE REVIEW

**Comment by rbouqueau** [comment]
It's ok but moving the CEAC block at a different location means the diff is not useful for this section.

**Comment by rcottingham** [comment]
Thanks Romain. What would you like me to do? Cancel this PR and resubmit with diff in existing place?

**Comment by rbouqueau** [comment]
Any works. If you push a second commit I can git-"squash" (ie merge all the commits of the PR into one).

**Comment by rbouqueau** [comment]
Superseeded by #52 and #54. Closing.

**Pull request closed without merging**
